---
database:
  name: registronavale
  user: registronavale
  password: "{{ vault_database.password }}"
  host: postgres


containers:

  - name: postgres
    image: postgres:9.5
    env:
      POSTGRES_DB: "{{ database.name }}"
      POSTGRES_USER: "{{ database.user }}"
      POSTGRES_PASSWORD: "{{ database.password }}"

  - name: django
    image: jcassee/registronavale
    env:
      WEB_DOMAIN: api.registronavale.com
    vars:
      database: "{{ database }}"
      admin_password: "pbkdf2_sha256$24000$qrS3syRl9Zp2$bV2DN6WNYPiCui4gDx453GLrHvXF2ZhOMntXBVMgQ5w="  # already hashed, no need for vault
    links:
      - postgres

  - name: halbrowser
    image: jcassee/hal-browser
    env:
      WEB_DOMAIN: browser.registronavale.com
    vars:
      entry_point: http://api.registronavale.com/

  - name: sslterm
    image: jcassee/nginx-sslterm
    vars:
      ssl_certificate: "{{ ssl_chain }}"
      ssl_certificate_key: "{{ ssl_private_key }}"
      ssl_trusted_certificate: "{{ ssl_rooted_chain }}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
