---
- name: Initialize Ansible
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Add SSH private key into ssh-agent
    shell: echo "{{ ssh_private_key }}" | ssh-add -
    no_log: yes
    when: "{{ add_ssh_key | default(False) | bool }}"
    changed_when: no

- name: Deploy Docker containers
  hosts: docker
  roles:
    - role: docker_containers
      remove_unknown_containers: yes
