---
- name: Initialize Ansible
  hosts: localhost
  roles:
    - role: init

- name: Deploy Docker containers
  hosts: docker
  roles:
    - role: docker_containers
      remove_unknown_containers: yes
