# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='ship_registry.Company')),
            ],
        ),
        migrations.AddField(
            model_name='shipownership',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='ship_registry.Ship'),
        ),
    ]
