# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship_registry', '0003_migrate_ownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='owner',
        ),
    ]
